version: "3"
services:
  rust-app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile
    container_name: my-rust-app
    volumes:
      - .:/app
    ports:
      - "4000:4000" # Adjust the port as needed
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis
      - REDIS_WORK_QUEUE=sanity_custom_sync_rust
      - PORT=4000
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379" # Expose the default Redis port
